#!/bin/bash

help(){
    printf "Presents a checklist of packages from the official Arch repo,\n"
    printf "the AUR, and the packages in the arch-pkgs subdirectory.\n"
    printf "Additionally installs configuration repositories.\n"
    printf "\n "
    printf "The actual work is in the Makefile. It handles the dependencies\n"
    printf "and knows how to install from the arch-pkgs repo (another make) or\n"
    printf "the AUR or a regular repo with a Makefile.\n"
    printf "The official repo is accessed by the meta-packages in arch-pkgs\n"
    printf "The aur packages are installed directly by the Makefile. \n"
    printf "Make calls make for each of the configuration repos as needed.\n"
    printf "\n "
    printf "In reality this is just a nice front end to the Makefile.\n"
    printf "You may almost as easily install everthing as you wish from \n"
    printf "the command line by using make. Doing that will give much more\n"
    printf "granular control.\n"
    printf "\n "
    printf "Some options require sudo. Just rerun this and choose only them,\n"
    printf "Or run them directly with sudo make.\n"
    printf "\n "
    printf "Options: \n"
    printf "  -h  This help text.\n"
    exit
}

# $opt will hold the current option
opt=''
while getopts h opt; do
    # loop continues till options finished
    # see which pattern $opt matches...
    case $opt in
        (h)
            help
            ;;
	# matches a question mark
	# (and nothing else, see text)
        (\?)
            printf "Bad option:" # $*
            printf " "
            help
            return 1
            ;;
    esac
done

(( OPTIND > 1 )) && shift $(( OPTIND - 1 ))

### Set up logging ###
exec 1> >(tee "pkg-install.log")
exec 2> >(tee "pkg-install.log")

# create a menu.
cmd=(dialog --stdout --separate-output --checklist "Select Packages to install" 22 77 16)
options=(
    1 "Necessities - utilities, yay, etc." on
    2 "X11 - xorg, libreOffice, vivaldi, etc."    on
    3 "Xmonad - Haskell, xfce4-panel, etc." on
    4 "dot files - (.zsh, .Xresources, .icons, etc" on
    5 "Emacs, accomplices (isync, mu4e,...) and configuration"  on
    6 "Xfce"   off
    7 "development - clojure, python, ruby, racket, guile, etc."  on
    8 "Tablet - Pen stuff - krita, cellwriter, onboard..." on
    9 "Natural language - hunspell, languagetool, ..."   on
    10 "Mobile Studio Pro - Nvidia, hidpi"  off
    11 "High DPI screen, .Xresources mods, Resolution 3840x2160"    on
    12 "Xmonad Xsession (requires sudo)"    off
    13 "Account setup - dotfiles, emacs, Xmonad" off
    14 "Anbox - run android in a container" off
    15 "Enable Anbox - configure and enable the anbox daemons (requires sudo)" off
    14 "All"    off )

# display menu and get the choices
choices=$("${cmd[@]}" "${options[@]}")
# clear

for choice in ${choices[@]}
do
    case $choice in
        1)
            make necessities
            ;;
        2)
            make X11
            ;;
        3)
            make xmonad-setup
            ;;
        4)
            make dotfiles
            ;;
        5)
            make emacs-setup
            ;;
        6)
            make Xfce
            ;;
        7)
            make devel
            ;;
        8)
            make tablet
            ;;
        9)
            make natural-language
            ;;
        10)
            make mobile-studio-pro
            ;;
        11)
            make hidpi
            ;;
        12)
            make -C xmonad-setup xsession
            ;;
        13)
            make account
            ;;
        14)
            make anbox
            ;;
        15)
            make -C dotfiles enable-anbox
            ;;
        16)
            make all
            ;;
    esac
done
